-- Airport database for PlaneSpotter Pal
-- Source: OurAirports (https://ourairports.com/data/) - Public Domain
-- To regenerate with full dataset, run: scripts/generate_airports.lua
return {
    -- United States (50)
    { icao = "KATL", iata = "ATL", name = "Hartsfield-Jackson Atlanta International Airport", lat = 33.6367, lon = -84.4281, country = "US" },
    { icao = "KLAX", iata = "LAX", name = "Los Angeles International Airport", lat = 33.9425, lon = -118.4081, country = "US" },
    { icao = "KORD", iata = "ORD", name = "O'Hare International Airport", lat = 41.9742, lon = -87.9073, country = "US" },
    { icao = "KJFK", iata = "JFK", name = "John F. Kennedy International Airport", lat = 40.6413, lon = -73.7781, country = "US" },
    { icao = "KDFW", iata = "DFW", name = "Dallas/Fort Worth International Airport", lat = 32.8998, lon = -97.0403, country = "US" },
    { icao = "KDEN", iata = "DEN", name = "Denver International Airport", lat = 39.8561, lon = -104.6737, country = "US" },
    { icao = "KSFO", iata = "SFO", name = "San Francisco International Airport", lat = 37.6213, lon = -122.3790, country = "US" },
    { icao = "KLAS", iata = "LAS", name = "Harry Reid International Airport", lat = 36.0840, lon = -115.1537, country = "US" },
    { icao = "KSEA", iata = "SEA", name = "Seattle-Tacoma International Airport", lat = 47.4502, lon = -122.3088, country = "US" },
    { icao = "KMCO", iata = "MCO", name = "Orlando International Airport", lat = 28.4312, lon = -81.3081, country = "US" },
    { icao = "KEWR", iata = "EWR", name = "Newark Liberty International Airport", lat = 40.6895, lon = -74.1745, country = "US" },
    { icao = "KMIA", iata = "MIA", name = "Miami International Airport", lat = 25.7959, lon = -80.2870, country = "US" },
    { icao = "KBOS", iata = "BOS", name = "Boston Logan International Airport", lat = 42.3656, lon = -71.0096, country = "US" },
    { icao = "KMSP", iata = "MSP", name = "Minneapolis-Saint Paul International Airport", lat = 44.8848, lon = -93.2223, country = "US" },
    { icao = "KDTW", iata = "DTW", name = "Detroit Metropolitan Wayne County Airport", lat = 42.2124, lon = -83.3534, country = "US" },
    { icao = "KPHL", iata = "PHL", name = "Philadelphia International Airport", lat = 39.8721, lon = -75.2411, country = "US" },
    { icao = "KIAH", iata = "IAH", name = "George Bush Intercontinental Airport", lat = 29.9902, lon = -95.3368, country = "US" },
    { icao = "KFLL", iata = "FLL", name = "Fort Lauderdale-Hollywood International Airport", lat = 26.0742, lon = -80.1506, country = "US" },
    { icao = "KBWI", iata = "BWI", name = "Baltimore/Washington International Airport", lat = 39.1754, lon = -76.6684, country = "US" },
    { icao = "KDCA", iata = "DCA", name = "Ronald Reagan Washington National Airport", lat = 38.8512, lon = -77.0402, country = "US" },
    { icao = "KSLC", iata = "SLC", name = "Salt Lake City International Airport", lat = 40.7884, lon = -111.9778, country = "US" },
    { icao = "KSAN", iata = "SAN", name = "San Diego International Airport", lat = 32.7336, lon = -117.1897, country = "US" },
    { icao = "KTPA", iata = "TPA", name = "Tampa International Airport", lat = 27.9755, lon = -82.5332, country = "US" },
    { icao = "KPDX", iata = "PDX", name = "Portland International Airport", lat = 45.5898, lon = -122.5951, country = "US" },
    { icao = "KSTL", iata = "STL", name = "St. Louis Lambert International Airport", lat = 38.7487, lon = -90.3700, country = "US" },
    { icao = "KCLT", iata = "CLT", name = "Charlotte Douglas International Airport", lat = 35.2140, lon = -80.9431, country = "US" },
    { icao = "KAUS", iata = "AUS", name = "Austin-Bergstrom International Airport", lat = 30.1975, lon = -97.6664, country = "US" },
    { icao = "KBNA", iata = "BNA", name = "Nashville International Airport", lat = 36.1263, lon = -86.6774, country = "US" },
    { icao = "KPIT", iata = "PIT", name = "Pittsburgh International Airport", lat = 40.4915, lon = -80.2329, country = "US" },
    { icao = "KMKE", iata = "MKE", name = "Milwaukee Mitchell International Airport", lat = 42.9472, lon = -87.8966, country = "US" },
    { icao = "KSMF", iata = "SMF", name = "Sacramento International Airport", lat = 38.6954, lon = -121.5908, country = "US" },
    { icao = "KSAT", iata = "SAT", name = "San Antonio International Airport", lat = 29.5337, lon = -98.4698, country = "US" },
    { icao = "KCLE", iata = "CLE", name = "Cleveland Hopkins International Airport", lat = 41.4117, lon = -81.8498, country = "US" },
    { icao = "KOAK", iata = "OAK", name = "Oakland International Airport", lat = 37.7213, lon = -122.2208, country = "US" },
    { icao = "KRDU", iata = "RDU", name = "Raleigh-Durham International Airport", lat = 35.8776, lon = -78.7875, country = "US" },
    { icao = "KIND", iata = "IND", name = "Indianapolis International Airport", lat = 39.7173, lon = -86.2944, country = "US" },
    { icao = "KCVG", iata = "CVG", name = "Cincinnati/Northern Kentucky International Airport", lat = 39.0488, lon = -84.6678, country = "US" },
    { icao = "KMCI", iata = "MCI", name = "Kansas City International Airport", lat = 39.2976, lon = -94.7139, country = "US" },
    { icao = "KSJC", iata = "SJC", name = "San Jose International Airport", lat = 37.3626, lon = -121.9291, country = "US" },
    { icao = "KONT", iata = "ONT", name = "Ontario International Airport", lat = 34.0560, lon = -117.6012, country = "US" },
    { icao = "KBUF", iata = "BUF", name = "Buffalo Niagara International Airport", lat = 42.9405, lon = -78.7322, country = "US" },
    { icao = "KABQ", iata = "ABQ", name = "Albuquerque International Sunport", lat = 35.0402, lon = -106.6092, country = "US" },
    { icao = "KTUS", iata = "TUS", name = "Tucson International Airport", lat = 32.1161, lon = -110.9410, country = "US" },
    { icao = "KOMA", iata = "OMA", name = "Eppley Airfield", lat = 41.3032, lon = -95.8941, country = "US" },
    { icao = "KELP", iata = "ELP", name = "El Paso International Airport", lat = 31.8072, lon = -106.3778, country = "US" },
    { icao = "PANC", iata = "ANC", name = "Ted Stevens Anchorage International Airport", lat = 61.1743, lon = -149.9962, country = "US" },
    { icao = "PHNL", iata = "HNL", name = "Daniel K. Inouye International Airport", lat = 21.3187, lon = -157.9225, country = "US" },
    { icao = "PHOG", iata = "OGG", name = "Kahului Airport", lat = 20.8986, lon = -156.4305, country = "US" },
    { icao = "TJSJ", iata = "SJU", name = "Luis Munoz Marin International Airport", lat = 18.4394, lon = -66.0018, country = "US" },
    { icao = "KMDW", iata = "MDW", name = "Chicago Midway International Airport", lat = 41.7868, lon = -87.7522, country = "US" },
    -- Europe (30)
    { icao = "EGLL", iata = "LHR", name = "London Heathrow Airport", lat = 51.4700, lon = -0.4543, country = "GB" },
    { icao = "LFPG", iata = "CDG", name = "Paris Charles de Gaulle Airport", lat = 49.0097, lon = 2.5479, country = "FR" },
    { icao = "EHAM", iata = "AMS", name = "Amsterdam Airport Schiphol", lat = 52.3086, lon = 4.7639, country = "NL" },
    { icao = "EDDF", iata = "FRA", name = "Frankfurt am Main Airport", lat = 50.0379, lon = 8.5622, country = "DE" },
    { icao = "LEMD", iata = "MAD", name = "Adolfo Suarez Madrid-Barajas Airport", lat = 40.4936, lon = -3.5668, country = "ES" },
    { icao = "LEBL", iata = "BCN", name = "Barcelona-El Prat Airport", lat = 41.2971, lon = 2.0785, country = "ES" },
    { icao = "LIRF", iata = "FCO", name = "Leonardo da Vinci-Fiumicino Airport", lat = 41.8003, lon = 12.2389, country = "IT" },
    { icao = "EGKK", iata = "LGW", name = "London Gatwick Airport", lat = 51.1537, lon = -0.1821, country = "GB" },
    { icao = "EDDM", iata = "MUC", name = "Munich Airport", lat = 48.3538, lon = 11.7861, country = "DE" },
    { icao = "LSZH", iata = "ZRH", name = "Zurich Airport", lat = 47.4647, lon = 8.5492, country = "CH" },
    { icao = "EKCH", iata = "CPH", name = "Copenhagen Kastrup Airport", lat = 55.6181, lon = 12.6560, country = "DK" },
    { icao = "ENGM", iata = "OSL", name = "Oslo Gardermoen Airport", lat = 60.1939, lon = 11.1004, country = "NO" },
    { icao = "ESSA", iata = "ARN", name = "Stockholm Arlanda Airport", lat = 59.6519, lon = 17.9186, country = "SE" },
    { icao = "EFHK", iata = "HEL", name = "Helsinki-Vantaa Airport", lat = 60.3172, lon = 24.9633, country = "FI" },
    { icao = "EIDW", iata = "DUB", name = "Dublin Airport", lat = 53.4213, lon = -6.2701, country = "IE" },
    { icao = "EGCC", iata = "MAN", name = "Manchester Airport", lat = 53.3537, lon = -2.2750, country = "GB" },
    { icao = "EBBR", iata = "BRU", name = "Brussels Airport", lat = 50.9014, lon = 4.4844, country = "BE" },
    { icao = "LOWW", iata = "VIE", name = "Vienna International Airport", lat = 48.1103, lon = 16.5697, country = "AT" },
    { icao = "LPPT", iata = "LIS", name = "Lisbon Humberto Delgado Airport", lat = 38.7813, lon = -9.1359, country = "PT" },
    { icao = "LGAV", iata = "ATH", name = "Athens Eleftherios Venizelos Airport", lat = 37.9364, lon = 23.9445, country = "GR" },
    { icao = "LTFM", iata = "IST", name = "Istanbul Airport", lat = 41.2753, lon = 28.7519, country = "TR" },
    { icao = "LKPR", iata = "PRG", name = "Vaclav Havel Airport Prague", lat = 50.1008, lon = 14.2600, country = "CZ" },
    { icao = "EPWA", iata = "WAW", name = "Warsaw Chopin Airport", lat = 52.1657, lon = 20.9671, country = "PL" },
    { icao = "LHBP", iata = "BUD", name = "Budapest Ferenc Liszt International Airport", lat = 47.4369, lon = 19.2556, country = "HU" },
    { icao = "LIMC", iata = "MXP", name = "Milan Malpensa Airport", lat = 45.6306, lon = 8.7231, country = "IT" },
    { icao = "LFPO", iata = "ORY", name = "Paris Orly Airport", lat = 48.7233, lon = 2.3794, country = "FR" },
    { icao = "EDDB", iata = "BER", name = "Berlin Brandenburg Airport", lat = 52.3667, lon = 13.5033, country = "DE" },
    { icao = "EDDL", iata = "DUS", name = "Dusseldorf Airport", lat = 51.2895, lon = 6.7668, country = "DE" },
    { icao = "EGSS", iata = "STN", name = "London Stansted Airport", lat = 51.8850, lon = 0.2350, country = "GB" },
    { icao = "LEPA", iata = "PMI", name = "Palma de Mallorca Airport", lat = 39.5517, lon = 2.7388, country = "ES" },
    -- Asia-Pacific (20)
    { icao = "VHHH", iata = "HKG", name = "Hong Kong International Airport", lat = 22.3080, lon = 113.9185, country = "HK" },
    { icao = "RJTT", iata = "HND", name = "Tokyo Haneda Airport", lat = 35.5494, lon = 139.7798, country = "JP" },
    { icao = "RJAA", iata = "NRT", name = "Narita International Airport", lat = 35.7647, lon = 140.3864, country = "JP" },
    { icao = "WSSS", iata = "SIN", name = "Singapore Changi Airport", lat = 1.3502, lon = 103.9944, country = "SG" },
    { icao = "RKSI", iata = "ICN", name = "Incheon International Airport", lat = 37.4602, lon = 126.4407, country = "KR" },
    { icao = "VTBS", iata = "BKK", name = "Suvarnabhumi Airport", lat = 13.6900, lon = 100.7501, country = "TH" },
    { icao = "RPLL", iata = "MNL", name = "Ninoy Aquino International Airport", lat = 14.5086, lon = 121.0198, country = "PH" },
    { icao = "WMKK", iata = "KUL", name = "Kuala Lumpur International Airport", lat = 2.7456, lon = 101.7099, country = "MY" },
    { icao = "VIDP", iata = "DEL", name = "Indira Gandhi International Airport", lat = 28.5562, lon = 77.1000, country = "IN" },
    { icao = "VABB", iata = "BOM", name = "Chhatrapati Shivaji Maharaj International Airport", lat = 19.0896, lon = 72.8656, country = "IN" },
    { icao = "ZBAA", iata = "PEK", name = "Beijing Capital International Airport", lat = 40.0799, lon = 116.6031, country = "CN" },
    { icao = "ZSPD", iata = "PVG", name = "Shanghai Pudong International Airport", lat = 31.1443, lon = 121.8083, country = "CN" },
    { icao = "ZGGG", iata = "CAN", name = "Guangzhou Baiyun International Airport", lat = 23.3924, lon = 113.2988, country = "CN" },
    { icao = "RCTP", iata = "TPE", name = "Taiwan Taoyuan International Airport", lat = 25.0777, lon = 121.2325, country = "TW" },
    { icao = "YSSY", iata = "SYD", name = "Sydney Kingsford Smith Airport", lat = -33.9461, lon = 151.1772, country = "AU" },
    { icao = "YMML", iata = "MEL", name = "Melbourne Airport", lat = -37.6733, lon = 144.8433, country = "AU" },
    { icao = "NZAA", iata = "AKL", name = "Auckland Airport", lat = -37.0082, lon = 174.7850, country = "NZ" },
    { icao = "VOMM", iata = "MAA", name = "Chennai International Airport", lat = 12.9941, lon = 80.1709, country = "IN" },
    { icao = "VOBL", iata = "BLR", name = "Kempegowda International Airport", lat = 13.1979, lon = 77.7063, country = "IN" },
    { icao = "WIII", iata = "CGK", name = "Soekarno-Hatta International Airport", lat = -6.1256, lon = 106.6559, country = "ID" },
}
